version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  Install:
    - location: scripts/setup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: root
