version: 0.0
os: centOS
files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    echo "test before install"
    # - location: script/cleanup.sh
    #   timeout: 300
    #   runas: root
  AfterInstall:
   - location: script/setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: script/run.sh
     timeout: 300
     runas: root
