version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/cleanup.sh
      timeout: 300
      runas: root
  Install:
    - location: script/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/run.sh
      timeout: 300
      runas: root
